--drop table DIM_promotion;
--alter session set current_schema = DW_DATA;

CREATE TABLE DIM_promotion(
    promotion_ID NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY,     
    promotion_name             VARCHAR2(50),
    promotion_media_type       VARCHAR2(30),  
    promotion_metric_amount    DECIMAL (10,2),
    department_name            VARCHAR2(50),
    promotion_price            DECIMAL (10,2),
    promotion_KPI              VARCHAR2(30),
    promotion_distinct_percent DECIMAL (10,2),

    CONSTRAINT "PK_T.DIM_promotion" PRIMARY KEY(promotion_ID) 
);