--drop table DIM_location;
--alter session set current_schema = DW_DATA;

CREATE TABLE DIM_location(
    country_ID NUMBER(22) GENERATED BY DEFAULT ON NULL AS IDENTITY,     
    part_desc             VARCHAR2(200),
    region_desc           VARCHAR2(200),
    country_desc          VARCHAR2(200),

    CONSTRAINT "PK_T.DIM_location" PRIMARY KEY(country_ID) 
);