--ALTER USER u_dw_references quota unlimited on TS_REFERENCES_DATA_01;
--DROP TABLE t_quarters;
alter session set current_schema=u_dw_references;

Create table t_quarters (
QUARTER_ID                      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY, 
DAYS_IN_CAL_QUARTER           NUMBER,
BEG_OF_CAL_QUARTER            DATE,
END_OF_CAL_QUARTER            DATE,
CALENDAR_QUARTER_NUMBER       VARCHAR2(1),
CONSTRAINT "PK_DW.T_QUARTER" PRIMARY KEY ( QUARTER_ID ) USING INDEX TABLESPACE ts_references_idx_01
);

select * from t_quarters;