--drop table DIM_gen_period;
--alter session set current_schema = DW_DATA;

CREATE TABLE DIM_gen_period(
    gen_period_ID NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY,     
    promotion_ID          NUMBER(10),
    promotion_description VARCHAR2(50),
    promotion_start       Date,
    promotion_end         Date,

    CONSTRAINT "PK_T.DIM_gen_period" PRIMARY KEY(gen_period_ID) 
);