--drop table DIM_agency;
--alter session set current_schema = DW_DATA;

CREATE TABLE DIM_agency(
    agency_ID NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY,     
    agency_name         VARCHAR2(50),
    department_name     VARCHAR2(50),
    agency_city         VARCHAR2(30),
    agency_address      VARCHAR2(50),
    agency_postcode     VARCHAR2(6),
    agency_email        VARCHAR2(30),
    agency_office_phone VARCHAR2(30),
    agency_mobile_phone VARCHAR2(30),
    agency_Fee_percent  DECIMAL(10,2),    
    agency_VAT_percent  DECIMAL(10,2),   

    CONSTRAINT "PK_T.DIM_agency" PRIMARY KEY(agency_ID) 
);
