--drop table DIM_product;
--alter session set current_schema = DW_DATA;

CREATE TABLE DIM_product(
    product_ID NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY,     
    brand_name           VARCHAR2(50),
    product_name         VARCHAR2(50),
    categoty_name        VARCHAR2(50),
    subcategory_name     VARCHAR2(50),
    promotion_name       VARCHAR2(50),
    promotion_media_type VARCHAR2(30),
 
    CONSTRAINT "PK_T.DIM_product" PRIMARY KEY(product_ID) 
);