--drop table FCT_business;
--alter session set current_schema = DW_DATA;

CREATE TABLE FCT_business(
    Business_Fact_ID NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY,   
    country_ID                             NUMBER(10),
    TIME_ID                                DATE,
    customer_ID                            NUMBER(10),
    employee_ID                            NUMBER(10),
    agency_ID                              NUMBER(10),
    gen_period_ID                          NUMBER(10),
    product_ID                             NUMBER(10),
    promotion_ID                           NUMBER(10),
    gross_profit_dollar_amount             DECIMAL (30,2),
    net_profit_dollar_amount               DECIMAL (30,2),
    gross_revenue_dollar_amount            DECIMAL (30,2),
    net_revenue_dollar_amount              DECIMAL (30,2),
    gross_cost_dollar_amount               DECIMAL (30,2),
    net_cost_dollar_amount                 DECIMAL (30,2),
    gross_salary_employee_dollar_amount    DECIMAL (30,2),
    net_salary_employee_dollar_amount      DECIMAL (30,2),
    customer_quantity                      DECIMAL (30,2),
    employee_quantity                      DECIMAL (30,2),
    promotion_quantity                     DECIMAL (30,2),
    revenue_cost_percent                   DECIMAL (10,2),

    CONSTRAINT "PK_T.FCT_business" PRIMARY KEY(Business_Fact_ID) 
);

ALTER TABLE FCT_business
   ADD CONSTRAINT "FK_FCT_business_DIM_location" FOREIGN KEY (country_ID )REFERENCES dim_location (country_ID);

ALTER TABLE FCT_business
   ADD CONSTRAINT "FK_FCT_business_DIM_date" FOREIGN KEY (TIME_ID )REFERENCES dim_date (TIME_ID);
   
ALTER TABLE FCT_business
   ADD CONSTRAINT "FK_FCT_business_DIM_customer" FOREIGN KEY (customer_ID )REFERENCES dim_customer (customer_ID);
   
ALTER TABLE FCT_business
   ADD CONSTRAINT "FK_FCT_business_DIM_employee" FOREIGN KEY (employee_ID )REFERENCES dim_employee (employee_ID);
   
ALTER TABLE FCT_business
   ADD CONSTRAINT "FK_FCT_business_DIM_agency" FOREIGN KEY (agency_ID )REFERENCES dim_agency (agency_ID);
   
ALTER TABLE FCT_business
   ADD CONSTRAINT "FK_FCT_business_DIM_gen_period" FOREIGN KEY (gen_period_ID )REFERENCES dim_gen_period (gen_period_ID);
   
ALTER TABLE FCT_business
   ADD CONSTRAINT "FK_FCT_business_DIM_product" FOREIGN KEY (product_ID )REFERENCES dim_product (product_ID);
   
ALTER TABLE FCT_business
   ADD CONSTRAINT "FK_FCT_business_DIM_promotion" FOREIGN KEY (promotion_ID )REFERENCES dim_promotion (promotion_ID);
   
